### ISSUE TITLE
box_ls() not working as expected

### ISSUE THREAD

**Issue by raahlstrom** [r-box/boxr#140]
I'm not sure if this has been asked before, I'm trying to pull a list of the contents of a folder in box. When I run the function, however, I receive the error

`Error in data.frame(name = x$name, type = x$type, id = x$id, size = x$size,  : 
  arguments imply differing number of rows: 1, 0`

Upon closer inspection, I realized that when a folder contains a link (for instance a link to a google drive spreadsheet) the function can't process it. I feel like I'm doing something wrong, any suggestions?

Thanks!

**Comment by nathancday** [comment]
Without having tried to re-create the error yet, I can tell you that we do not test for behavior with links (only files and sub-folders). So I wonder if links are an edge case and require some special handling to be added.

Just to be clear the folder structure looks like this:
- home (box_dir = 0)
- - folder1 (box_dir = 1)
- - - link
- - folder2 (box_dir = 2)
- - - file1.csv

And the behavior is:
`box_ls(1) # errors out`
`box_ls(2) # ok`

**Comment by raahlstrom** [comment]
I realize this is kind of a weird exception, thanks for the quick reply! Yes, box_ls works with folder2, but not folder1. If there is a link anywhere in the directory it throws the error, even if the directory includes other files/directories.

**Comment by nathancday** [comment]
Great, thanks for that useful information. I'll take a look and see what's causing the links to break things.

**Comment by nathancday** [comment]
Looks like the issue was being caused because links don't carry all of the same attributes that files/folders do. I think it's resolved now via better handling of missing values in boxr's S3 methods.  If you can, please take the branch `link-woes` for a test drive, `remotes::install_github("r-box/boxr@link-woes")` and let me know.

**Comment by raahlstrom** [comment]
I just tested it, and it works for my use case! Thank you so much!!

**Comment by nathancday** [comment]
Let's leave this open for now until we actually merge the fixes back into master

**Comment by MokeEire** [comment]
I am still experiencing this issue.  Has it been fixed?

## Input

```
library(tidyverse)
library(boxr)

box_auth() # Uses environment variables

box_getwd() # This works
box_ls()
```

## Output

```
Error in data.frame(name = x$name, type = x$type, id = x$id, size = x$size,  : 
  arguments imply differing number of rows: 1, 0
```

**Comment by raahlstrom** [comment]
Yes, but I dont believe it's in CRAN so you'll need to  use the version on github.

`devtools::install_github("r-box/boxr")`

That's at least what worked for me!
